// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Deal Pilot — own Supabase project (migrated off Lovable 2026-05-16)
const SUPABASE_URL = "https://fatynhxuzsdyoczbpkno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhdHluaHh1enNkeW9jemJwa25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4OTIyNjEsImV4cCI6MjA5NDQ2ODI2MX0.Okz0W-eqS_BRksOe224dKcyOG7nH3z18aHbvUVFJOXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
